### ISSUE TITLE
提交两点疑问：wifkey和 import memo 模块

### ISSUE THREAD

**Issue by tanlentboy** [zhangpanyi/btsmonitor#1]
#1.请教一下作者，config.yml中的
````
# 帐号名称
account: "YOUACCOUNT"
# 帐号私钥
wifkey: "YOUBITSHARESWIF"
````

这个私钥是 活动私钥还是账户私钥呢？ 这个地方有个疑问就是，btsmoniter 好像具备监控，转账，查看备注的功能，但是要实现这三个功能，只配置一个私钥好像是不行的，比如要查看备注memo，必须要单独的备注私钥才能查看，转账的时候，也必须要有备注私钥才能转账，但是这里配置文件中只配置了一个私钥，请教一下这里是如何实现的呢？
#2.  transfer.py 中
```
# -*- coding:utf-8 -*- 

import asyncio
import logging
from . import statistics
from graphenebase import memo as BtsMemo
from graphenebase import PublicKey, PrivateKey

```
这里的  graphenebase 是否有问题？ 我使用docker一直没成功允许过，一直报错 import memo 模块错误

修改为 
from bitsharesbase import memo as BtsMemo
from bitsharesbase.account import PublicKey, PrivateKey
之后，docker 运行正常。

**Comment by zhangpanyi** [comment]
私钥是活动权限的私钥，我的活动权限私钥和备注私钥是一样的。

第二个问题可能是bitsharesbase这个库更新了吧，我有时间检查一下。

获取 Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by tanlentboy** [comment]
谢谢🙏张老师贡献并开源了这个btsmoniter源码，这个程序比bts官方理事会的python-bitshares相比，直接封装成了docker，对于python不熟的方便太多了，张老师cnblog和csdn都不更新了，无法加入讨论组，遗憾

**Comment by zhangpanyi** [comment]
功能比python-bitshares还是少太多，这是一个针对我应用场景而开发的库而不是一个通用库，如果有其它需求还得需要自进行修改。优点就是python-bitshares不支持并发，我把全部网络操作改为了异步。

获取 Outlook for Android<https://aka.ms/ghei36>

________________________________
