### ISSUE TITLE
请教一下张老师，如何判断btsmoniter是否正常工作了

### ISSUE THREAD

**Issue by tanlentboy** [zhangpanyi/btsmonitor#4]
张老师，有没有办法测试btsmoniter是否正常工作呢？ws节点测试网络通畅。通过docker logs -f 打印日志能看到transfer.py 处理接收到的的充值，但是数据库里面没有。数据库连接信息没错，没法在docker里面查看的mysql相关信息。另外RPC通信除了通过防火墙进行限制从而使得安全以外，能否添加client和server 之间秘钥的方式来获得安全保障呢

**Comment by zhangpanyi** [comment]
你在logger.py文件里面的__handler_request函数里面加点日志看一看，循环里面有没有从队列里取出数据来，然后再看一下await conn.execute(log)的执行结果。
________________________________
发件人: tanlentboy <notifications@github.com>
发送时间: 2018年2月21日 8:30
收件人: zhangpanyi/btsmonitor
抄送: Subscribed
主题: [zhangpanyi/btsmonitor] 请教一下张老师，如何判断btsmoniter是否正常工作了 (#4)


张老师，有没有办法测试btsmoniter是否正常工作呢？ws节点测试网络通畅。通过docker logs -f 打印日志能看到transfer.py 处理接收到的的充值，但是数据库里面没有。数据库连接信息没错，没法在docker里面查看的mysql相关信息。

―

**Comment by zhangpanyi** [comment]
一般情况RPC通信是应该加密的，这里是因为btsmonitor服务和红包服务在同一台机器，而btsmonitor服务的端口并没有对外开放，所以觉得没有这个需求。
________________________________
发件人: tanlentboy <notifications@github.com>
发送时间: 2018年2月21日 8:30
收件人: zhangpanyi/btsmonitor
抄送: Subscribed
主题: [zhangpanyi/btsmonitor] 请教一下张老师，如何判断btsmoniter是否正常工作了 (#4)


张老师，有没有办法测试btsmoniter是否正常工作呢？ws节点测试网络通畅。通过docker logs -f 打印日志能看到transfer.py 处理接收到的的充值，但是数据库里面没有。数据库连接信息没错，没法在docker里面查看的mysql相关信息。

―

**Comment by tanlentboy** [comment]
问题解决，谢谢张老师
