### ISSUE TITLE
btsmoniter #memo 讨论

### ISSUE THREAD

**Issue by tanlentboy** [zhangpanyi/btsmonitor#5]
@zhangpanyi   对于充值memo 会不会有这个场景呢？ 就是举个例：A用户的telegram id是 ：12345678 充值到 bts地址，转账的时候结果memo 备注粗心的写成了 12345679  。 实际上这个 12345679 这个id也有一个对应的 telegram 用户。恰好这个id为 12345679的用户也是telegram红包的用户，那么他说不定有可能会提现而造成不必要的麻烦。

PS：这个只是题外探讨而已哈。用户自己充值而造成的错误，这个肯定用户自己的问题。 张老师我看充值之后有插入数据库的记录 
`// 插入操作记录
		desc := fmt.Sprintf("您充值*%.2f* *%s*已确认, 区块高度: *%d*", float64(req.GetAmount())/100.0,`
没有添加 使用机器人主动推送充值信息到 telegram用户（知道tg id可以使用机器人直接通过id发送给用户消息）   是不是就是为了避免用户填写错memo的原因而不主动推送消息呢

**Comment by zhangpanyi** [comment]
倒不是为了避免填写错memo的原因而不推送消息，只是单纯的没做这个功能。不过这是一个很有用的功能，应该加上。

**Comment by tanlentboy** [comment]
@zhangpanyi 老师，报告个问题。某个用户充值了 5cny，然后发放红包，其他用户领取红包的时候，显示  您领取了XXXX发放的红包(id: *100001*), 获得*1* *CNY* 随机的红包数目这个是正确的，然后用户余额也是正确的。但是这个领取红包的用户查看历史记录的时候，显示的领取的红包的数目是发放红包的用户的充值数目 5cny，肯定不对， 历史记录里面显示的数目肯定是读取数据库的，由于对go还不熟，对占位符这块搞了半天没搞明白怎么修改这个问题。

**Comment by zhangpanyi** [comment]
感谢提醒，已修复这个问题，不过之前的历史记录就懒得修复了。
